name: Despliegue AutomÃ¡tico Murcia Energia Solar

on:
  push:
    branches:
      - main  # AsegÃºrate de que tu rama se llama main, si es master cÃ¡mbialo aquÃ­

jobs:
  web-deploy:
    name: Subiendo archivos a Raiola
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Descargando cÃ³digo desde GitHub
      uses: actions/checkout@v3

    - name: ðŸ“‚ Sincronizando con el servidor via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./public_html/
        dangerous-clean-slate: false
        protocol: ftp
